##########################################
# Instal KIRIES stack
##########################################
- name: Install KIRIES [add syslog-ng key]
  apt_key:
    url: http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng/Debian_8.0/Release.key

- name: Install KIRIES [add source list]
  apt_repository:
    repo: "deb http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng/Debian_8.0 ./"

- name: Install KIRIES [install syslog-ng]
  apt:
    name: "{{ item }}"
    update_cache: true
  with_items:
    - syslog-ng-core
    - syslog-ng-mod-riemann

- name: Install KIRIES [install clojure]
  get_url: url=https://raw.githubusercontent.com/technomancy/leiningen/2.5.1/bin/lein
           dest=/usr/bin/lein
           mode=0755
