---
- hosts: app
  remote_user: root
  handlers:
    - name: reload crudtest
      shell: sudo service crudtest restart --force

  tasks:
  - name: prepare dir
    file: path={{ project_dir }} mode=0777 state=directory

  - name: pull app
    git: repo={{ project_repo }} dest={{ project_root }} version={{ branch }}

  # - name: flyway conf
  #   template: src=templates/flyway.conf.j2 dest={{ project_root }}/flyway.conf
  - name: install deps
    shell: npm install
    args:
      chdir: "{{project_root}}"

  - name: Create Crudtest service
    template: src=templates/daemon.j2 dest=/etc/init.d/crudtest group=root owner=root mode=0777
    tags: 'config'
    notify:
      - reload crudtest

  - name: reload crudtest
    shell: service crudtest restart --force
