user: root

dbuser: crudtest
project_dir: /opt
project_root: /opt/crudtest
project_repo: https://github.com/devops-ru/delivery-pipeline-training 
branch: master

riemann_server: 127.0.0.1

flyway_root: /opt/flyway
flyway_config:
  database:
    host: localhost
    port: 5432
    dbms: postgesql
    name: "{{ dbuser }}"
    user: "{{ dbpassword }}"
    password: postgres
  schemas: public, myschema
flyway_locations: /var/www/site/migrations
